### ISSUE TITLE
Install on shared hosting

### ISSUE THREAD

**Issue by sgorki** [leopku/revel#2]
I need tutorial to install revel on shared hosting

**Comment by leopku** [comment]
It's sorry that this project was deprecated. 
I'm very glad that you are interesting for this project. And there will another forum project if you can wait for it.

It's recommended that using this project in a VPS but not a shared hosting, even if it can.
If you wan to deploy it to a shared hosting, you should find a parse-service provider and rebuild this project from source code.

**Comment by sgorki** [comment]
Okay, i have a Centos 7 vps. So how to install ?

**Comment by leopku** [comment]
Simplest way is install via Docker. 

  1. Install Docker in your VPS.

  2. Clone source code to your VPS.

  3. Install and run a mongo container/instance.

  4. Run `docker build -t leopku/revel . ` in root of source code.

  5. Run `docker run -itd --name revel -p 1337:1337 -p 4040:4040 -p 43554:43554 leopku/revel`

  6. Visit `:4040` via browser

If your are not family with Docker, you can find tutorials from search engine.
